"""station details

Revision ID: 114139dc923d
Revises: e5ac329026a3
Create Date: 2026-10-08 10:06:09.949016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '114139dc923d'
down_revision: Union[str, Sequence[str], None] = 'e5ac329026a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stations', sa.Column('region', sa.String(length=160), server_default=sa.text("''"), nullable=False))
    op.add_column('stations', sa.Column('site_type', sa.String(length=160), server_default=sa.text("''"), nullable=False))
    op.add_column('stations', sa.Column('land_status', sa.String(length=160), server_default=sa.text("''"), nullable=False))
    op.add_column('stations', sa.Column('landlord', sa.String(length=255), server_default=sa.text("''"), nullable=False))
    op.add_column('stations', sa.Column('opened_at', sa.Date(), nullable=True))
    op.add_column('stations', sa.Column('grid_company', sa.String(length=255), server_default=sa.text("''"), nullable=False))
    op.add_column('stations', sa.Column('tp_number', sa.String(length=64), server_default=sa.text("''"), nullable=False))
    op.add_column('stations', sa.Column('transformer_kva', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('stations', sa.Column('allocated_kw', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('stations', sa.Column('voltage', sa.String(length=64), server_default=sa.text("''"), nullable=False))
    op.add_column('stations', sa.Column('connection_contract', sa.String(length=128), server_default=sa.text("''"), nullable=False))
    op.add_column('stations', sa.Column('connection_date', sa.Date(), nullable=True))
    op.add_column('stations', sa.Column('meter_number', sa.String(length=128), server_default=sa.text("''"), nullable=False))
    op.add_column('stations', sa.Column('energy_supplier', sa.String(length=255), server_default=sa.text("''"), nullable=False))
    op.add_column('stations', sa.Column('has_canopy', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('stations', sa.Column('has_lighting', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('stations', sa.Column('has_cctv', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('stations', sa.Column('has_internet', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('stations', sa.Column('internet_type', sa.String(length=128), server_default=sa.text("''"), nullable=False))
    op.add_column('stations', sa.Column('has_fence', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('stations', sa.Column('has_wc', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('stations', sa.Column('has_cafe', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('stations', sa.Column('has_signage', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('stations', sa.Column('accessible', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('stations', sa.Column('parking_spots', sa.Integer(), nullable=True))
    op.add_column('stations', sa.Column('surface_type', sa.String(length=128), server_default=sa.text("''"), nullable=False))
    op.add_column('stations', sa.Column('has_operator', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('stations', sa.Column('staff_count', sa.Integer(), nullable=True))
    op.add_column('stations', sa.Column('work_schedule', sa.String(length=128), server_default=sa.text("''"), nullable=False))
    op.add_column('stations', sa.Column('responsible_name', sa.String(length=160), server_default=sa.text("''"), nullable=False))
    op.add_column('stations', sa.Column('responsible_phone', sa.String(length=64), server_default=sa.text("''"), nullable=False))
    op.add_column('stations', sa.Column('service_company', sa.String(length=255), server_default=sa.text("''"), nullable=False))
    op.add_column('stations', sa.Column('notes', sa.Text(), server_default=sa.text("''"), nullable=False))
    op.add_column('stations', sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'custom')
    op.drop_column('stations', 'notes')
    op.drop_column('stations', 'service_company')
    op.drop_column('stations', 'responsible_phone')
    op.drop_column('stations', 'responsible_name')
    op.drop_column('stations', 'work_schedule')
    op.drop_column('stations', 'staff_count')
    op.drop_column('stations', 'has_operator')
    op.drop_column('stations', 'surface_type')
    op.drop_column('stations', 'parking_spots')
    op.drop_column('stations', 'accessible')
    op.drop_column('stations', 'has_signage')
    op.drop_column('stations', 'has_cafe')
    op.drop_column('stations', 'has_wc')
    op.drop_column('stations', 'has_fence')
    op.drop_column('stations', 'internet_type')
    op.drop_column('stations', 'has_internet')
    op.drop_column('stations', 'has_cctv')
    op.drop_column('stations', 'has_lighting')
    op.drop_column('stations', 'has_canopy')
    op.drop_column('stations', 'energy_supplier')
    op.drop_column('stations', 'meter_number')
    op.drop_column('stations', 'connection_date')
    op.drop_column('stations', 'connection_contract')
    op.drop_column('stations', 'voltage')
    op.drop_column('stations', 'allocated_kw')
    op.drop_column('stations', 'transformer_kva')
    op.drop_column('stations', 'tp_number')
    op.drop_column('stations', 'grid_company')
    op.drop_column('stations', 'opened_at')
    op.drop_column('stations', 'landlord')
    op.drop_column('stations', 'land_status')
    op.drop_column('stations', 'site_type')
    op.drop_column('stations', 'region')
    # ### end Alembic commands ###
