"""documents

Revision ID: d9836f6b0ee1
Revises: a6c8f4c393e5
Create Date: 2026-10-08 12:59:24.843806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9836f6b0ee1'
down_revision: Union[str, Sequence[str], None] = 'a6c8f4c393e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Последовательность для номеров серий. Alembic её не замечает при
    # автогенерации, а таблица на неё ссылается — создаём вручную и первой.
    op.execute("CREATE SEQUENCE IF NOT EXISTS document_series_seq")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('doc_number', sa.String(length=128), nullable=False),
    sa.Column('doc_date', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('original_name', sa.String(length=500), nullable=False),
    sa.Column('stored_name', sa.String(length=160), nullable=False),
    sa.Column('mime', sa.String(length=160), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('series_id', sa.BigInteger(), server_default=sa.text("nextval('document_series_seq')"), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    op.create_index('ix_documents_series_current', 'documents', ['series_id', 'is_current'], unique=False)
    op.create_index(op.f('ix_documents_series_id'), 'documents', ['series_id'], unique=False)
    op.create_index(op.f('ix_documents_station_id'), 'documents', ['station_id'], unique=False)
    op.create_index('ix_documents_station_type', 'documents', ['station_id', 'doc_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_station_type', table_name='documents')
    op.drop_index(op.f('ix_documents_station_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_series_id'), table_name='documents')
    op.drop_index('ix_documents_series_current', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
    op.execute("DROP SEQUENCE IF EXISTS document_series_seq")
