"""chargers

Revision ID: e5ac329026a3
Revises: b4dd1260ba52
Create Date: 2026-10-08 08:34:14.025929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5ac329026a3'
down_revision: Union[str, Sequence[str], None] = 'b4dd1260ba52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chargers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vendor', sa.String(length=160), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('serial', sa.String(length=128), nullable=False),
    sa.Column('ocpp_id', sa.String(length=128), nullable=False),
    sa.Column('power_kw', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('current_type', sa.String(length=8), nullable=False),
    sa.Column('connectors', sa.String(length=255), nullable=False),
    sa.Column('connector_count', sa.Integer(), nullable=True),
    sa.Column('tariff_rub', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('installed_at', sa.Date(), nullable=True),
    sa.Column('warranty_until', sa.Date(), nullable=True),
    sa.Column('last_service_at', sa.Date(), nullable=True),
    sa.Column('service_interval_months', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chargers_ocpp_id'), 'chargers', ['ocpp_id'], unique=False)
    op.create_index(op.f('ix_chargers_serial'), 'chargers', ['serial'], unique=False)
    op.create_index(op.f('ix_chargers_station_id'), 'chargers', ['station_id'], unique=False)
    op.create_index(op.f('ix_chargers_status'), 'chargers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chargers_status'), table_name='chargers')
    op.drop_index(op.f('ix_chargers_station_id'), table_name='chargers')
    op.drop_index(op.f('ix_chargers_serial'), table_name='chargers')
    op.drop_index(op.f('ix_chargers_ocpp_id'), table_name='chargers')
    op.drop_table('chargers')
    # ### end Alembic commands ###
